### ISSUE TITLE
Process Error while running models simultaneously in multiple threads 

### ISSUE THREAD

**Issue by vikasjagtap** [jaamsim/jaamsim#15]
I am trying to run models simultaneously on multiple threads using same config file by using new API. Following method is invoked in multiple threads. I removed some input settings which differ per run. I cannot share the config file as it is proprietary work. And I have no other config files to test my code with. 

I am using `2019-05` release.

```
private void runTest(String item) throws InterruptedException {
        CountDownLatch countDownLatch = new CountDownLatch(1);

        JaamSimModel sim = new JaamSimModel("test-" + item);
        sim.autoLoad();

        InputAgent.readResource(sim, "./test.cfg");
        sim.setInput("Simulation", "PrintReport", "FALSE");

        //Set some input for the run

        EventTimeListener listener = new EventTimeListener() {
            @Override
            public void tickUpdate(long tick) {
            }
            @Override
            public void timeRunning() {
                if (EventManager.current().isRunning()) {
                    return;
                }
                countDownLatch.countDown();
            }
            @Override
            public void handleError(Throwable t) {
                log.error(t.getMessage(), t);
                countDownLatch.countDown();
            }
        };
        sim.setTimeListener(listener);
        sim.start();
        countDownLatch.await();
    }
```

But I am getting following exception:
```
com.jaamsim.events.ProcessError: Tried to schedule using an EventHandle already in use
	at com.jaamsim.events.EventManager.scheduleTicks(EventManager.java:820)
	at com.jaamsim.events.EventManager.scheduleTicks(EventManager.java:791)
	at com.jaamsim.ProcessFlow.Device.startStep(Device.java:141)
	at com.jaamsim.ProcessFlow.Device.restart(Device.java:65)
	at com.jaamsim.ProcessFlow.Device.thresholdChanged(Device.java:379)
	at com.jaamsim.Thresholds.Threshold$ThresholdChangedTarget.process(Threshold.java:134)
	at com.jaamsim.events.EventManager.executeTarget(EventManager.java:172)
	at com.jaamsim.events.EventManager.execute(EventManager.java:256)
	at com.jaamsim.events.Process.run(Process.java:101)
```

It will be great if someone could give me pointers why it is happening.

Thanks
Vikas

**Comment by dharryking** [comment]
This bug was fixed in release 2019-09. See the release notes for details.
