### ISSUE TITLE
Error running on MacOS

### ISSUE THREAD

**Issue by saem** [jaamsim/jaamsim#32]
Built both `master` and the `v2022-07-jogltest1` branches, and ran with the following command: `java --add-exports java.desktop/sun.awt=ALL-UNNAMED -jar build/jars/JaamSim2022-07.jar`

Got the following errors in the terminal:
```
2023-01-27 19:44:16.692 java[42476:728243] NSWindow does not support NSWindowCollectionBehaviorFullScreenPrimary for utility windows
2023-01-27 19:44:16.724 java[42476:728243] NSWindow does not support NSWindowCollectionBehaviorFullScreenPrimary for utility windows
2023-01-27 19:44:16.750 java[42476:728243] NSWindow does not support NSWindowCollectionBehaviorFullScreenPrimary for utility windows
2023-01-27 19:44:16.767 java[42476:728243] NSWindow does not support NSWindowCollectionBehaviorFullScreenPrimary for utility windows
com.jogamp.opengl.GLException: Thread[#36,RenderThread,5,main] glGetError() returned the following error codes after a call to glCreateShader(<int> 0x8B31): Unknown glGetError() return value: ( 1286 0x506), 
	at com.jogamp.opengl.DebugGL4bc.writeGLError(DebugGL4bc.java:31781)
	at com.jogamp.opengl.DebugGL4bc.glCreateShader(DebugGL4bc.java:3498)
	at com.jaamsim.render.Shader.<init>(Shader.java:46)
	at com.jaamsim.render.Renderer.createCoreShader(Renderer.java:675)
	at com.jaamsim.render.Renderer.initCoreShaders(Renderer.java:780)
	at com.jaamsim.render.Renderer.initSharedContext(Renderer.java:887)
	at com.jaamsim.render.Renderer.mainRenderLoop(Renderer.java:237)
	at com.jaamsim.render.Renderer.access$000(Renderer.java:91)
	at com.jaamsim.render.Renderer$1.run(Renderer.java:202)
	at java.base/java.lang.Thread.run(Thread.java:1589)

2023-01-27 19:44:18.190 java[42476:728243] NSWindow does not support NSWindowCollectionBehaviorFullScreenPrimary for utility windows
```

And the following error dialog text:
> Thread[#36,RenderState,5,main] glGetError() returned the following error codes after a call to glCreateshader(<int> 0x8B31): Unknown glGetError() return value: ( 1286, 0x506), 

Note: I had to type the above by hand as I couldn't copy paste, and the message seems to be cut off.

* CPU M1, 2020
* OS: 11.4
* openjdk: 19.0.2 2023-01-17

**Comment by hharrison** [comment]
Thanks so much for testing, any chance you could try again with the update pushed to the jogl_update branch of the repo? Small additional debug patch included to try and track down the problem by printing on stdout.

**Comment by hbjorkedal** [comment]
Reopening this thread as it seems OP wont respond. I get the same error when running both the normal and the java --add-exports java.desktop/sun.awt=ALL-UNNAMED -jar JaamSim2023-07.jar command. Tried every version from 2023-06-macfix to the most recent 2024-02

java -jar JaamSim2023-07.jar
2024-02-23 12:38:24.913 java[41230:5646590] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.
2024-02-23 12:38:31.807 java[41230:5646590] NSWindow does not support NSWindowCollectionBehaviorFullScreenPrimary for utility windows
2024-02-23 12:38:31.817 java[41230:5646590] NSWindow does not support NSWindowCollectionBehaviorFullScreenPrimary for utility windows
2024-02-23 12:38:31.825 java[41230:5646590] NSWindow does not support NSWindowCollectionBehaviorFullScreenPrimary for utility windows
2024-02-23 12:38:31.855 java[41230:5646590] NSWindow does not support NSWindowCollectionBehaviorFullScreenPrimary for utility windows
^Cjava.lang.ThreadDeath
        at java.base/java.lang.Thread.stop(Thread.java:937)
        at com.jogamp.newt.opengl.GLWindow$GLLifecycleHook$1.run(GLWindow.java:762)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at com.jogamp.common.util.SecurityUtil.doPrivileged(SecurityUtil.java:82)
        at com.jogamp.newt.opengl.GLWindow$GLLifecycleHook.shutdownRenderingAction(GLWindow.java:757)
        at jogamp.newt.WindowImpl.shutdown(WindowImpl.java:664)
        at jogamp.newt.WindowImpl.shutdownAll(WindowImpl.java:128)
        at jogamp.newt.DisplayImpl$1.run(DisplayImpl.java:77)
        at com.jogamp.nativewindow.NativeWindowFactory.shutdown(NativeWindowFactory.java:329)
        at com.jogamp.nativewindow.NativeWindowFactory$1$1.run(NativeWindowFactory.java:234)
        at java.base/java.lang.Thread.run(Thread.java:829)

java.lang.ThreadDeath
        at java.base/java.lang.Thread.stop(Thread.java:937)
        at com.jogamp.newt.opengl.GLWindow$GLLifecycleHook$1.run(GLWindow.java:762)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at com.jogamp.common.util.SecurityUtil.doPrivileged(SecurityUtil.java:82)
        at com.jogamp.newt.opengl.GLWindow$GLLifecycleHook.shutdownRenderingAction(GLWindow.java:757)
        at jogamp.newt.WindowImpl.shutdown(WindowImpl.java:664)
        at jogamp.newt.WindowImpl.shutdownAll(WindowImpl.java:128)
        at jogamp.newt.DisplayImpl$1.run(DisplayImpl.java:77)
        at com.jogamp.nativewindow.NativeWindowFactory.shutdown(NativeWindowFactory.java:329)
        at com.jogamp.nativewindow.NativeWindowFactory$1$1.run(NativeWindowFactory.java:234)
        at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by hharrison** [comment]
Hmmm, the updated JOGL version we pulled in for version 2023-07 generally solved these issues for other Mac users. I'm aware of the NSWindow warnings, but they shouldn't affect the software working as intended. Are you reporting this because of the exception backlog (our shutdown hooks in jaamsim are not the cleanest to be fair and sometimes generates this backtrace but shouldn't have any effect on the functionality) Or is there an actual problem using the software?

**Comment by hbjorkedal** [comment]
I cant use the software at all. No matter what I try the GUI stops responding after startup. Ive tried jpk 8, 11 and 21 with no success.  Ive also tried it with both the commands listed on the download page. Below is a view of how it looks after startup. I can move the windows around, but the second my mouse overs the inside of the windows its starts a spinner on my mouse indicating its not responding. 
![Skjermbilde 2024-02-23 kl  18 37 50](https://github.com/jaamsim/jaamsim/assets/143625335/b5308804-f81b-48fe-baab-7be5bd088540)

**Comment by hharrison** [comment]
OK, can you confirm which java version/distribution you're using and what version of MacOS, and I guess any details about what specific machine you have would also be helpful to start narrowing this down. 

Harvey

**Comment by hharrison** [comment]
Complete shot in the dark, but could you add the following to the java commandline on startup, I've seen some other reports on Sonoma that have serious issues in their current releases:

-Dsun.java2d.metal=false
-Dsun.java2d.opengl=true

**Comment by hbjorkedal** [comment]
I'm on a 2020 M1 Macbook Air running Sonoma 14.3.1. Ive tried using both homebrew and downloading directly from java.com. Currently I have Java 8 downloaded from java.com installed. 
java -jar -Dsun.java2d.metal=false -Dsun.java2d.opengl=true Jaamsim2024-02.jar running this still made no difference. Its still not responding directly after startup.

**Comment by hbjorkedal** [comment]
Got some more info that might help. Tried to run the dsun commands after the jaapsim.jar and jaapsim tried to load it as configs. Since I didn't have any file named it didn't open any and I got access to the log viewer displaying this:
![Skjermbilde 2024-02-23 kl  19 25 04](https://github.com/jaamsim/jaamsim/assets/143625335/5742f642-cf23-42cd-96fc-6d5602849e0a)
Looks like the initial startup causes no error. When I try to make a New file in the drop down menu it crashes again

**Comment by hharrison** [comment]
OK, the metal and opengl options are only for java 17 and above and I don't think exist in the java 8 vm. Just to confirm:

(from the logbook you sent it is a Metal backed open GL driver on your machine, which frankly is full of problems and of pretty terrible quality)

FAILS on Java 8 :
java -jar JaamSim2024-02.jar

Please try (degrading to the safegraphics option which uses a very limited OpenGL subset)
java -jar JaamSim2024-02.jar -sg

On Java 17 (or above), if you can try, would be helpful:
java --add-exports java.desktop/sun.awt=ALL-UNNAMED -jar JaamSim2024-02.jar
java -Dsun.java2d.metal=false --add-exports java.desktop/sun.awt=ALL-UNNAMED -jar JaamSim2024-02.jar
java --add-exports java.desktop/sun.awt=ALL-UNNAMED -jar JaamSim2024-02.jar -sg

**Comment by hharrison** [comment]
The warnings you have there are uninteresting.

When you run the above, essentially the program just freezes after startup? Or can't be interacted with? Or the 3d content window never appears? Can you be a bit more specific on what the problem actually is?

**Comment by hharrison** [comment]
The contents of the log viewer (if possible) from each of those tests would be interesting.

**Comment by hbjorkedal** [comment]
Yes, exactly. All of the commands above start the program but freezes on startup. 
So they all appear as the first screenshot I sent of the open program. But the GUI is not responding. Unfortunately, I cant get access to the logs either as the entire menu freezes as well. The rest of my Mac functions as normal.

**Comment by hbjorkedal** [comment]
The windows can be moved around though, just the content within that freezes up.

**Comment by hharrison** [comment]
It's going to be a bit difficult to diagnose further without more information, are you familiar at all with the visualvm or jstack tools that allow a dump of the threadstack to be captured? It appears my Mac pro x86-64 doesn't hit this issue and seems to work just fine.

Here's some high level instructions on how to capture a threadstack from a running java program, if you're able to capture the stack while the program is unresponsive that would really help tracking down the issue.

https://www.mastertheboss.com/java/how-to-capture-a-thread-dump-in-java/

**Comment by hbjorkedal** [comment]
[
[threaddump.txt](https://github.com/jaamsim/jaamsim/files/14390123/threaddump.txt)
] 

Here you go!

**Comment by hharrison** [comment]
Can I just confirm a few things:

- I assume Jaamsim opens initially and you can see the main 3d content window, the deadlock only occurs when opening the examples window?
- Have you successfully run Jaamsim previously? Is this an issue after a java version change or a MacOS update or is this an issue in an updated Jaamsim version?
- Assuming you've previously been running it successfully, can you provide the last version that ran successfully, including macos, java and jaamsim version.

Thanks!

Harvey

**Comment by peterfig** [comment]
Hey I'm getting this error now.  It *sometimes* happens when I run the program.   It *always* happens when I use File --> Open, when loading the selected model.  However, I can open all of the examples from the help menu.   Here's what ChatGPT said about this error:

The error you're encountering, "NSWindow does not support NSWindowCollectionBehaviorFullScreenPrimary for utility windows", is related to how macOS handles window behavior and fullscreen modes, specifically for utility windows. It seems that your GLWindow is being treated as a utility window, but utility windows don't support the fullscreen behavior you are trying to use.

In your Java program, make sure that you are not setting your GLWindow to be a utility window (this might happen implicitly or explicitly depending on your code). Look for any calls related to NSWindow or the window style and change the behavior to something that supports fullscreen (i.e., a normal window).

If you specifically need your window to be a utility window (for example, if it’s a smaller floating window), avoid trying to set it to fullscreen. Instead, you could try adjusting the window size or behavior to work within the constraints of utility windows.

**Comment by peterfig** [comment]
2025-04-09 12:54:01
Full thread dump OpenJDK 64-Bit Server VM (11.0.15+10-LTS mixed mode):

Threads class SMR info:
_java_thread_list=0x0000600000c548c0, length=21, elements={
0x00007fddd8874c00, 0x00007fddd8877200, 0x00007fddc8977000, 0x00007fddc8975a00,
0x00007fddc8977600, 0x00007fddd8878e00, 0x00007fddc9808200, 0x00007fddd8879400,
0x00007fddca149600, 0x00007fddd8918000, 0x00007fddd8cd0800, 0x00007fddca14f600,
0x00007fdda883b800, 0x00007fddd8fc7600, 0x00007fdda9812600, 0x00007fddac8f0a00,
0x00007fddc983ac00, 0x00007fddc8978000, 0x00007fddc9862a00, 0x00007fdd8915de00,
0x00007fdda8d0c000
}

"Reference Handler" #2 daemon prio=10 os_prio=31 cpu=2.52ms elapsed=175.98s tid=0x00007fddd8874c00 nid=0x4803 waiting on condition  [0x0000000304e0c000]
   java.lang.Thread.State: RUNNABLE
        at java.lang.ref.Reference.waitForReferencePendingList(java.base@11.0.15/Native Method)
        at java.lang.ref.Reference.processPendingReferences(java.base@11.0.15/Reference.java:241)
        at java.lang.ref.Reference$ReferenceHandler.run(java.base@11.0.15/Reference.java:213)

"Finalizer" #3 daemon prio=8 os_prio=31 cpu=4.31ms elapsed=175.98s tid=0x00007fddd8877200 nid=0x5503 in Object.wait()  [0x0000000304f0f000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(java.base@11.0.15/Native Method)
        - waiting on <no object reference available>
        at java.lang.ref.ReferenceQueue.remove(java.base@11.0.15/ReferenceQueue.java:155)
        - waiting to re-lock in wait() <0x0000000400000be0> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(java.base@11.0.15/ReferenceQueue.java:176)
        at java.lang.ref.Finalizer$FinalizerThread.run(java.base@11.0.15/Finalizer.java:170)

"Signal Dispatcher" #4 daemon prio=9 os_prio=31 cpu=0.68ms elapsed=175.97s tid=0x00007fddc8977000 nid=0x5e03 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Service Thread" #5 daemon prio=9 os_prio=31 cpu=0.03ms elapsed=175.97s tid=0x00007fddc8975a00 nid=0x7903 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #6 daemon prio=9 os_prio=31 cpu=4849.61ms elapsed=175.97s tid=0x00007fddc8977600 nid=0x7703 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"C1 CompilerThread0" #9 daemon prio=9 os_prio=31 cpu=1807.57ms elapsed=175.97s tid=0x00007fddd8878e00 nid=0x6303 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"Sweeper thread" #10 daemon prio=9 os_prio=31 cpu=31.86ms elapsed=175.97s tid=0x00007fddc9808200 nid=0x7403 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Common-Cleaner" #11 daemon prio=8 os_prio=31 cpu=3.06ms elapsed=175.92s tid=0x00007fddd8879400 nid=0x6f03 in Object.wait()  [0x0000000305734000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(java.base@11.0.15/Native Method)
        - waiting on <no object reference available>
        at java.lang.ref.ReferenceQueue.remove(java.base@11.0.15/ReferenceQueue.java:155)
        - waiting to re-lock in wait() <0x0000000400001060> (a java.lang.ref.ReferenceQueue$Lock)
        at jdk.internal.ref.CleanerImpl.run(java.base@11.0.15/CleanerImpl.java:148)
        at java.lang.Thread.run(java.base@11.0.15/Thread.java:829)
        at jdk.internal.misc.InnocuousThread.run(java.base@11.0.15/InnocuousThread.java:161)

"AppKit Thread" #12 daemon prio=5 os_prio=31 cpu=2883.71ms elapsed=175.64s tid=0x00007fddca149600 nid=0x103 runnable  [0x000000030456f000]
   java.lang.Thread.State: RUNNABLE
        at sun.lwawt.macosx.LWCToolkit.doAWTRunLoopImpl(java.desktop@11.0.15/Native Method)
        at sun.lwawt.macosx.LWCToolkit.doAWTRunLoop(java.desktop@11.0.15/LWCToolkit.java:929)
        at sun.lwawt.macosx.LWCToolkit.invokeAndWait(java.desktop@11.0.15/LWCToolkit.java:710)
        at sun.lwawt.macosx.LWCToolkit.invokeAndWait(java.desktop@11.0.15/LWCToolkit.java:655)
        at sun.lwawt.macosx.CAccessibility.invokeAndWait(java.desktop@11.0.15/CAccessibility.java:94)
        at sun.lwawt.macosx.CAccessibility.getFocusOwner(java.desktop@11.0.15/CAccessibility.java:548)

"AWT-Shutdown" #13 prio=5 os_prio=31 cpu=1.43ms elapsed=175.58s tid=0x00007fddd8918000 nid=0xfa03 in Object.wait()  [0x000000030593a000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(java.base@11.0.15/Native Method)
        - waiting on <no object reference available>
        at java.lang.Object.wait(java.base@11.0.15/Object.java:328)
        at sun.awt.AWTAutoShutdown.run(java.desktop@11.0.15/AWTAutoShutdown.java:291)
        - waiting to re-lock in wait() <0x00000004000030c0> (a java.lang.Object)
        at java.lang.Thread.run(java.base@11.0.15/Thread.java:829)

"Java2D Queue Flusher" #14 daemon prio=10 os_prio=31 cpu=660.86ms elapsed=175.40s tid=0x00007fddd8cd0800 nid=0x15207 in Object.wait()  [0x0000000305837000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(java.base@11.0.15/Native Method)
        - waiting on <no object reference available>
        at sun.java2d.opengl.OGLRenderQueue$QueueFlusher.run(java.desktop@11.0.15/OGLRenderQueue.java:205)
        - waiting to re-lock in wait() <0x0000000400001498> (a sun.java2d.opengl.OGLRenderQueue$QueueFlusher)
        at java.lang.Thread.run(java.base@11.0.15/Thread.java:829)

"Java2D Disposer" #15 daemon prio=10 os_prio=31 cpu=10.12ms elapsed=175.35s tid=0x00007fddca14f600 nid=0x11603 in Object.wait()  [0x0000000305d69000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(java.base@11.0.15/Native Method)
        - waiting on <no object reference available>
        at java.lang.ref.ReferenceQueue.remove(java.base@11.0.15/ReferenceQueue.java:155)
        - waiting to re-lock in wait() <0x0000000400001ca8> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(java.base@11.0.15/ReferenceQueue.java:176)
        at sun.java2d.Disposer.run(java.desktop@11.0.15/Disposer.java:144)
        at java.lang.Thread.run(java.base@11.0.15/Thread.java:829)

"RefreshThread" #16 daemon prio=5 os_prio=31 cpu=12.06ms elapsed=174.76s tid=0x00007fdda883b800 nid=0x1570b in Object.wait()  [0x0000000305e6c000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(java.base@11.0.15/Native Method)
        - waiting on <no object reference available>
        at com.jaamsim.controllers.RateLimiter.run(RateLimiter.java:58)
        - waiting to re-lock in wait() <0x0000000400003fa8> (a java.lang.Object)
        at java.lang.Thread.run(java.base@11.0.15/Thread.java:829)

"AWT-EventQueue-0" #18 prio=6 os_prio=31 cpu=3957.14ms elapsed=174.67s tid=0x00007fddd8fc7600 nid=0x1602f in Object.wait()  [0x0000000306070000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(java.base@11.0.15/Native Method)
        - waiting on <no object reference available>
        at java.lang.Object.wait(java.base@11.0.15/Object.java:328)
        at jogamp.nativewindow.macosx.OSXUtil.RunOnMainThread(OSXUtil.java:318)
        - waiting to re-lock in wait() <0x000000043bad4560> (a java.lang.Object)
        at jogamp.nativewindow.macosx.OSXUtil.CreateNSWindow(OSXUtil.java:161)
        at jogamp.nativewindow.jawt.macosx.MacOSXJAWTWindow.lockSurfaceImpl(MacOSXJAWTWindow.java:311)
        at com.jogamp.nativewindow.awt.JAWTWindow.lockSurface(JAWTWindow.java:708)
        at com.jogamp.newt.awt.NewtCanvasAWT.addNotify(NewtCanvasAWT.java:621)
        - locked <0x000000043d86bf90> (a java.lang.Object)
        at java.awt.Container.addNotify(java.desktop@11.0.15/Container.java:2800)
        - locked <0x00000004003ad638> (a java.awt.Component$AWTTreeLock)
        at java.awt.Window.addNotify(java.desktop@11.0.15/Window.java:786)
        - locked <0x00000004003ad638> (a java.awt.Component$AWTTreeLock)
        at java.awt.Frame.addNotify(java.desktop@11.0.15/Frame.java:490)
        - locked <0x00000004003ad638> (a java.awt.Component$AWTTreeLock)
        at java.awt.Window.show(java.desktop@11.0.15/Window.java:1048)
        at java.awt.Component.show(java.desktop@11.0.15/Component.java:1716)
        at java.awt.Component.setVisible(java.desktop@11.0.15/Component.java:1663)
        at java.awt.Window.setVisible(java.desktop@11.0.15/Window.java:1031)
        at com.jaamsim.render.Renderer$3.run(Renderer.java:623)
        at java.awt.event.InvocationEvent.dispatch(java.desktop@11.0.15/InvocationEvent.java:313)
        at java.awt.EventQueue.dispatchEventImpl(java.desktop@11.0.15/EventQueue.java:770)
        at java.awt.EventQueue$4.run(java.desktop@11.0.15/EventQueue.java:721)
        at java.awt.EventQueue$4.run(java.desktop@11.0.15/EventQueue.java:715)
        at java.security.AccessController.doPrivileged(java.base@11.0.15/Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@11.0.15/ProtectionDomain.java:85)
        at java.awt.EventQueue.dispatchEvent(java.desktop@11.0.15/EventQueue.java:740)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(java.desktop@11.0.15/EventDispatchThread.java:203)
        at java.awt.EventDispatchThread.pumpEventsForFilter(java.desktop@11.0.15/EventDispatchThread.java:124)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(java.desktop@11.0.15/EventDispatchThread.java:113)
        at java.awt.EventDispatchThread.pumpEvents(java.desktop@11.0.15/EventDispatchThread.java:109)
        at java.awt.EventDispatchThread.pumpEvents(java.desktop@11.0.15/EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.run(java.desktop@11.0.15/EventDispatchThread.java:90)

"RenderThread" #19 prio=5 os_prio=31 cpu=1554.53ms elapsed=174.20s tid=0x00007fdda9812600 nid=0x1670b waiting on condition  [0x0000000306411000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@11.0.15/Native Method)
        - parking to wait for  <0x0000000400060cc8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(java.base@11.0.15/LockSupport.java:194)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitUninterruptibly(java.base@11.0.15/AbstractQueuedSynchronizer.java:2018)
        at com.jaamsim.render.Renderer.mainRenderLoop(Renderer.java:409)
        at com.jaamsim.render.Renderer.access$000(Renderer.java:93)
        at com.jaamsim.render.Renderer$1.run(Renderer.java:203)
        at java.lang.Thread.run(java.base@11.0.15/Thread.java:829)

"RenderManagerThread" #24 prio=5 os_prio=31 cpu=259.82ms elapsed=172.80s tid=0x00007fddac8f0a00 nid=0x16423 in Object.wait()  [0x000000030630e000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(java.base@11.0.15/Native Method)
        - waiting on <no object reference available>
        at java.lang.Object.wait(java.base@11.0.15/Object.java:328)
        at com.jaamsim.controllers.RenderManager$RedrawCallback.waitForRedraw(RenderManager.java:246)
        - waiting to re-lock in wait() <0x0000000400060e10> (a com.jaamsim.controllers.RenderManager$RedrawCallback)
        at com.jaamsim.controllers.RenderManager.renderManagerLoop(RenderManager.java:513)
        at com.jaamsim.controllers.RenderManager.access$100(RenderManager.java:114)
        at com.jaamsim.controllers.RenderManager$1.run(RenderManager.java:136)
        at java.lang.Thread.run(java.base@11.0.15/Thread.java:829)

"TimerQueue" #28 daemon prio=5 os_prio=31 cpu=35.39ms elapsed=86.71s tid=0x00007fddc983ac00 nid=0xde03 waiting on condition  [0x0000000306fc6000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@11.0.15/Native Method)
        - parking to wait for  <0x000000043ac67b30> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(java.base@11.0.15/LockSupport.java:194)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@11.0.15/AbstractQueuedSynchronizer.java:2081)
        at java.util.concurrent.DelayQueue.take(java.base@11.0.15/DelayQueue.java:217)
        at javax.swing.TimerQueue.run(java.desktop@11.0.15/TimerQueue.java:171)
        at java.lang.Thread.run(java.base@11.0.15/Thread.java:829)

"DestroyJavaVM" #29 prio=5 os_prio=31 cpu=64196.11ms elapsed=86.66s tid=0x00007fddc8978000 nid=0x2803 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Timer-0" #41 daemon prio=6 os_prio=31 cpu=0.30ms elapsed=53.64s tid=0x00007fddc9862a00 nid=0x11f1f in Object.wait()  [0x0000000307252000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(java.base@11.0.15/Native Method)
        - waiting on <no object reference available>
        at java.util.TimerThread.mainLoop(java.base@11.0.15/Timer.java:553)
        - waiting to re-lock in wait() <0x000000043c8ac638> (a java.util.TaskQueue)
        at java.util.TimerThread.run(java.base@11.0.15/Timer.java:506)

"RenderThread-Display-.macosx_nil-1-EDT-5" #50 daemon prio=6 os_prio=31 cpu=175.84ms elapsed=41.17s tid=0x00007fdd8915de00 nid=0x27f47 in Object.wait()  [0x000000030770e000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(java.base@11.0.15/Native Method)
        - waiting on <no object reference available>
        at jogamp.newt.DefaultEDTUtil$NEDT.run(DefaultEDTUtil.java:355)
        - waiting to re-lock in wait() <0x000000043b808e30> (a java.util.ArrayList)

"Attach Listener" #51 daemon prio=9 os_prio=31 cpu=0.78ms elapsed=0.10s tid=0x00007fdda8d0c000 nid=0x200df waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"VM Thread" os_prio=31 cpu=19.86ms elapsed=175.99s tid=0x00007fddd8708cd0 nid=0x4f03 runnable

"GC Thread#0" os_prio=31 cpu=55.14ms elapsed=176.00s tid=0x00007fddc8705aa0 nid=0x3603 runnable

"GC Thread#1" os_prio=31 cpu=59.60ms elapsed=174.06s tid=0x00007fddaba89680 nid=0x1e523 runnable

"GC Thread#2" os_prio=31 cpu=45.58ms elapsed=174.06s tid=0x00007fddaba899c0 nid=0x1f213 runnable

"GC Thread#3" os_prio=31 cpu=49.09ms elapsed=174.06s tid=0x00007fddaba8a440 nid=0x1e42f runnable

"GC Thread#4" os_prio=31 cpu=54.16ms elapsed=174.06s tid=0x00007fddaba8aec0 nid=0x1e303 runnable

"GC Thread#5" os_prio=31 cpu=50.58ms elapsed=174.06s tid=0x00007fddaba8b940 nid=0x17403 runnable

"GC Thread#6" os_prio=31 cpu=52.99ms elapsed=174.06s tid=0x00007fddaba8c3c0 nid=0x1e203 runnable

"GC Thread#7" os_prio=31 cpu=50.52ms elapsed=174.06s tid=0x00007fddaba8ce40 nid=0x1e003 runnable

"GC Thread#8" os_prio=31 cpu=47.51ms elapsed=174.06s tid=0x00007fddaba8d8c0 nid=0x1df03 runnable

"G1 Main Marker" os_prio=31 cpu=1.56ms elapsed=176.00s tid=0x00007fddc8707830 nid=0x3303 runnable

"G1 Conc#0" os_prio=31 cpu=18.35ms elapsed=176.00s tid=0x00007fddc87086d0 nid=0x4103 runnable

"G1 Conc#1" os_prio=31 cpu=17.30ms elapsed=174.03s tid=0x00007fddaba8e340 nid=0x1da9f runnable

"G1 Refine#0" os_prio=31 cpu=0.79ms elapsed=176.00s tid=0x00007fddc8769230 nid=0x5403 runnable

"G1 Young RemSet Sampling" os_prio=31 cpu=23.12ms elapsed=176.00s tid=0x00007fddc876a0c0 nid=0x4303 runnable
"VM Periodic Task Thread" os_prio=31 cpu=86.62ms elapsed=175.92s tid=0x00007fddd8714310 nid=0x723f waiting on condition

JNI global refs: 749, weak refs: 891

**Comment by hharrison** [comment]
Could you also provide your command line for reference, and also consider trying with adding the -XstartOnFirstThread option to the JVM invocation, this is just a shot in the dark to see if it makes it any more reliable before going deeper in debugging this.

**Comment by hharrison** [comment]
I believe all of these should have been solved with the update to the 2.6.0 release of JOGL, if anyone is still experiencing these lockups with the JaamSim 2025-08 release or later, please re-open this report, but for now I will close this issue.
